'''
asigancion multiple:
Python nos permte colocar y asiganar variables variables dentro de una sola
a.b.c = 'hola'.True.23

DIR(String): Nos permite mirar las propiedades/funciones que tenemos con un String.
CONSEJO: usar print, para visualizar elcontenido previo que vamos a usasr, es decir, supongamos que vamos a creamos una funcion,
pero la funcion tadavia no esta creada. Como un mock-up.

DIFERENCIA ENTRE VARIABLE LOCAL/GLOBAL:
Una variable global es una variable que es declarada fuera de una funcion, mientras que la local es declarada dentor de una funcion
Si queremos usar una variable local como una variable global, usamos GLOBAL. Aunque se pueda hacer no lo extendamos,
es decir, lo usamos cuando la maenra de acceder a una variable local es muy complicada.
EJM:
def f1():
    # Ponemos global para poder usar esa variable
    global sumar
    sumar = a + b

print(f1)
print(sumar)

BIN: Es un procesador de texto 
Para ancenderlo podemos "vim pru.py"
Para salir ESC, despues ":wq!", guardar= ":w", salir= ":aq"




'''