#*Quiero que la versión del compose, sea la 3
version: "3"
#* el compose no entiende los contenedores como tal, sino como "servicios"
services:
    #*carpeta donde esta la imagen
    app:
        #* Imagen del docker
        image: flaskapp
        #* nombre del contenedor
        container_name: nombreContenedor
        #* Dependencia de: Si ponemos esto, estamos indicando que se inciará el contenedor solo si se inicia otro
        #*^Es decir, hasta que el otro contenedor/servicio este funcionando no me inicies este contenedor/servicio.
        #* En este caso con MONGO, nos srive para practicar, ya que tenemos atlas de mongo.
        depends_on: db
        #* Puertos
        ports:
            - "7000:5000"
            #* toma toda la información de la carpeta donde esta la imagen, y enviala a esta carpeta
            #* en este caso, la estamos volviendo a poner en la carpeta aPP, ya que como sabemos cuando nos
            #* salimos, los datos que teniamos se eliminan, por eso en un VOLUMEN ESPEJO. Ademñas de que nos sincronice los cambios
            #* que hagamos en local hacia la imagen.
        volumes:
            - ./src:/app


    db:
        image: mongo

#* Ahora en terminal, si ponemos:
#* docker-compose up -d // Nos iniciará el archivo del docker compose, pero si en vez de UP usamos DOWN. Nos bajará todo.
#* docker-compose ps // Nos permite ver los procesos que tenemos
#* dokcer-compose logs nombreCarpeta // Nos permite ver los procesos de esa carpeta, es decir, el servicio/contenedor especifíco. 

#* Si vemos que nos da problemas DOCKEr, ponemos en el iconico en la barra de tareas, RESTART.